// Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
//#include "PushNotificationPackage.h"
//#include "GestureHandlerPackage.h"
//#include "SafeAreaViewPackage.h"
//#include "RNCVideoPackage.h"
//#include "FastImagePackage.h"
//#include "PingPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(Package::Context ctx)
{
    return {
        std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen v1
//        std::make_shared<PushNotificationPackage>(ctx),
//        std::make_shared<GestureHandlerPackage>(ctx),
//        std::make_shared<SafeAreaViewPackage>(ctx),
//        std::make_shared<RNCVideoPackage>(ctx),
//        std::make_shared<FastImagePackage>(ctx),
//        std::make_shared<PingPackage>(ctx)
    };
}